name: CI

on: [pull_request]

jobs:
  packer_test:

    runs-on: ubuntu-latest
    container: mehdizonjy/packer-terraform-ansible
    steps:
    - uses: actions/checkout@v1
    - name: validate packer
      run: |
        packer validate packer.json
      env:
        DO_API_TOKEN: ${{ secrets.DO_TOKEN }}
        AUTOMATION_SSH_KEY: ${{ secrets.DO_AUTOMATION_SSH_SECRET }}

